export default [
  {
    title: "ducktape",
    isNew: true,
    image: "ducktape.png",
    priority: 6,
    isHoverMe: false,
  },
  {
    title: "portfoliov3",
    isNew: true,
    image: "portfoliov3.png",
    priority: 2,
    isHoverMe: false,
  },
  {
    title: "lesgrainsdesel",
    isNew: false,
    image: "lesgrainsdesel.png",
    priority: 5,
    isHoverMe: false,
  },
  {
    title: "buzzer",
    isNew: false,
    image: "buzzer.png",
    priority: 0,
    isHoverMe: false,
  },
  {
    title: "data handling for ratp",
    isNew: false,
    image: "vigicrue.png",
    priority: 0,
    isHoverMe: false,
  },
  {
    title: "machine learning labelling",
    isNew: false,
    image: "labelling.png",
    priority: 0,
    isHoverMe: false,
  },
  {
    title: "grapher",
    isNew: false,
    image: "grapher.png",
    priority: 0,
    isHoverMe: false,
  },
];
